test/oic_rp/rp/flows.py
Found some errors in test rp-19 to RP-22
=> Some minor changes made to the RP flows

test/oic_op/config_server/config_server.py, test/oic_op/config_server/htdocs/op_config.mako, test/oic_op/config_server/static/op_config.css, test/oic_op/rp/oprp2.py
Added Response Type and Supported features in config page + fixed bug in check_if_oprp_started (config_server) + more info in oprp logs
=> Added response_type and Sign + enc

test/oic_op/config_server/config.py.example, test/oic_op/config_server/config_server.py, test/oic_op/rp/oprp2.py
Added "testflow" attribute to config.py (config_server) and added logging when "testflows" module doesn't exist
=> tflow support in config_server + OPRP logging

test/oic_op/config_server/config_server.py, test/oic_op/config_server/default_oprp_config.py, test/oic_op/config_server/response_encoder.py, test/oic_rp/op/response_encoder.py, test/oic_rp/op/server.py
Added profile to the config server in order to make it easier to restart OPRP instances. Converted config_server to pep-8
=> Added profile + refactored variables and methods to pep-8 (config_server)

test/oic_op/config_server/htdocs/op_config.mako, test/oic_op/config_server/static/op_config.css, test/oic_op/config_server/static/op_config.js
Finished disco url check. Now it's not possible to go to the "client config" page without entering all required fields and a issuer url which doesn't contain .well-known/openid-configurations
=> Dynamic disco url check

test/oic_op/config_server/static_client_reg_port_db_editor.py
Added script for removing entries in static_client_registration_port_database
=> port database edit script (config server)

test/oic_op/config_server/config_server.py, test/oic_op/config_server/test_config_server.py
Extended logging in config_server and set logging level on the urllib3 lib to warning
=> Extended logging in config_server

test/oic_op/config_server/config_server.py, test/oic_op/config_server/htdocs/op_config.mako, test/oic_op/config_server/port_issuer_instance_id_database.py, test/oic_op/config_server/static/op_config.js
Fixed so the server doesn't crash when non ASCII characters are used in text fields. Refactored some variables names
=> Non ASCII characters bug

test/oic_op/config_server/config_server.py, test/oic_op/config_server/htdocs/op_config.mako, test/oic_op/config_server/static/op_config.css
Fixed confusing provider configuration instructions made it more user friendly
=> Provider metadata information

test/oic_op/config_server/port_database.py, test/oic_op/config_server/port_database_editor.py, test/oic_op/config_server/test_port_database_editor.py
port_database_editor now loads the config files as modules instead of strings
=> port_database_editor update

test/oic_op/config_server/config_server.py, test/oic_op/config_server/port_database_editor.py, test/oic_op/config_server/test_config_server.py, test/oic_op/config_server/test_port_database_editor.py
Now the config_server loads the existing config files as modules instead of reading them as strings
=> config_server now loads configuration files as modules

test/oic_op/rp/htdocs/flowlist.mako
Added zoom feature in OPRP flow list, while zooming out it's possible to get all tests on a single line.
=> Zoom feature

test/oic_op/config_server/port_database.py, test/oic_op/config_server/port_database_editor.py, test/oic_op/config_server/test_port_database_editor.py
port_database_editor: when generating a new port database the old one is removed.
=> port_database_editor fix

test/oic_op/config_server/config_server.py
Missed to return a value from validate_configuration_size
=> Missed to return a value from validate_configuration_size

doc/Makefile, doc/conf.py, doc/contents.rst, doc/how_to_use_rp_test.rst, doc/howto.rst, doc/index.rst, doc/install.rst, doc/make.bat, doc/make.sh
I have added the Apache License 2.0 heading with the link to the license by commenting on top of the files.
=> Added license information in the doc/ folder files

test/oic_op/config_server/port_database_editor.py, test/oic_op/config_server/test_port_database_editor.py
While synchronizing config files and the port database; if database entry exists in database but no configuration info then the info is added to the database
=> Sync config files and the port database fix

setup.py, test/oic_op/config_server/htdocs/test_instance_list.mako, test/oic_op/config_server/static/test_instance_list.js
Added information to test_instance_list page and added new packages to the setup.py file
=> Added info to user + setup.py update

src/configuration_server/shell_commands.py
Fixed "invalid literal for int() with base 10: '' " bug which occurred when while parsing the pid in kill_process function
=> Fixed pid bug

src/configuration_server/config_values.py, src/configuration_server/configurations.py, src/configuration_server/port_database_editor.py, src/configuration_server/shell_commands.py, src/configuration_server/test_instance_database.py, test/oic_op/config_server/config_server.py, test/oic_op/config_server/htdocs/test_instance_list.mako, test/oic_op/config_server/static/test_instance_list.js, unitest/config_server/test_configurations.py, unitest/config_server/test_instance_database.py, unitest/config_server/test_port_database_editor.py
Added contact information block in the test instance page at config_server.py
=> Added new field for adding contact email in registration page

INSTALL.txt
Signed-off-by: Hans Zandbelt <hans.zandbelt@zmartzone.eu>
=> add colons and test deployment

INSTALL.txt
Signed-off-by: Hans Zandbelt <hans.zandbelt@zmartzone.eu>
=> add another colon and confirm deployment
